### ISSUE TITLE
megamenu

### ISSUE THREAD

**Issue by jan-miksik** [gweicz/bankless#119]
- nefunguje při druhém kliknutí na detail článku
- v menu je i aktuálně zobrazený článek

**Comment by Vojtch159** [comment]
Myslíš že by se měl ten článek na kterém seš měl smazat z menu a nahradit jiným? Osobně se mi to moc nelíbí, že na každé podstránce to menu bude jiné.
Jinak ten bug s tím druhým kliknutím jsem fixnul.

**Comment by jan-miksik** [comment]
_v menu je i aktuálně zobrazený článek_ - No tohle byla spíš ta menší věc. Ono mi tolik nedávalo smysl mít v menu článek na kterém aktuálně jsem. Je to jako odkaz na stránku na které jsem. Jinak mi to příjde víceméně jedno...
