### ISSUE TITLE
Napojení sideBaru na instagram api

### ISSUE THREAD

**Issue by Vojtch159** [gweicz/bankless#38]
Koukal jsem se už na instagram api. Pravděpodobně nejlepší cesta je založení nějakého Basic instagram API co poskytuje facebook. Jen teda zatím se mi to nepovedlo založit, kvůli tomu že to chce nějaké ověření. Account na fb bych měl mít v pohodě tak nevím.
![image](https://user-images.githubusercontent.com/73985038/111870644-2e479c00-8986-11eb-933a-2b8f499238b2.png)
Tady je k tomu ještě dokumentace: https://developers.facebook.com/docs/instagram-basic-display-api
Co jsem koukal tak to basic api by mělo bohatě stačit, jen se musí nějak vyřešit to založení. 
Pokud by se vám to někomu povedlo založit a fungovalo to tak už to klidně můžu implementovat.

**Comment by Vojtch159** [comment]
Bohužel na privátním facebooku mi to hází ten samej problém co na cryptopanda facebooku. 
Napadá mě řešení přes nějaké neoficiální api. Zkusím se podívat jestli by třeba nebylo nějaké dobré pro naše použití.

**Comment by Vojtch159** [comment]
Takže jsem koukal na ty neoficiální api a bohužel nic. Všechno to využívá Jquery a bohužel nemůžu donutit next.js a Jquery, aby spolu byly kámoši...
Máte nějaké nápady? 
Asi bych to probral dneska na callu. @rixcian myslíš že bys to kdyžtak hodil do zápisu callu prosím?

**Comment by rixcian** [comment]
https://github.com/kasperlegarth/instastory.js

**Comment by rixcian** [comment]
https://lightwidget.com/
