### ISSUE TITLE
Bug: Při načtení článku bez tagu vyhodí web error

### ISSUE THREAD

**Issue by rixcian** [gweicz/bankless#52]
![image](https://user-images.githubusercontent.com/14358496/112722738-7c6f1900-8f0b-11eb-8ef6-824cd2e6dd1c.png)

Zkuste nějakému článku, který se zobrazuje na hlavní stránce odebrat všechny tagy a celá hlavní stránka vám spadne.

**Comment by Vojtch159** [comment]
A jak si myslíš že by měl bejt ten fix? Napadají mě 3 možnosti. 
a) Ten článek se prostě vůbec nezobrazí
b) Ten článek se zobrazí, dá se mu OSTATNÍ tag, pokud nebude mít fotku tak se mu dá bílá a nazdar.
c) Budeme doufat že nikoho nenapadne publishnout článek bez tagů nebo fotky.

Osobně bych byl pro možnosti a nebo c. Možnost b jsem teď zkoušel a vypadá to hrozně. 
![image](https://user-images.githubusercontent.com/73985038/112814807-f1fbf600-907f-11eb-8829-b02d18a42dbc.png)
